title: "xfbs:blog"
email: pelsen@xfbs.net
description: >-
  Personal blog of xfbs.
url: "https://blog.xfbs.net"
baseurl: ""
twitter_username: const_xfbs
github_username:  xfbs

# Build settings
markdown: kramdown
theme: tale
plugins:
  - jekyll-feed
  - jekyll-youtube
  - jekyll-typogrify

permalink: /posts/:year-:month-:day/:title
paginate: 25
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
